config:
  subprojects:
    libportal:
      dependencies:
        debian: &debian_libportal |
          sudo apt-get install -y \
          python3-dbusmock \
          python3-pytest \
          valac \
          protobuf-c-compiler \
          protobuf-compiler \
          libglib2.0 \
          libgtk-3-dev \
          libprotobuf-c-dev \
          libsystemd-dev \
          libgirepository1.0-dev

        ubuntu: *debian_libportal
