# SPDX-FileCopyrightText: 2024 Chris Rizzitello <sithlord48@gmail.com>
# SPDX-License-Identifier: MIT

name: "Install dependencies"

inputs:
  os-like:
    description: "Used only on Linux for distro type"

  qt-version:
    description: "The version of Qt to install on mac os"

  legacy-debian:
    description: "Use legacy debian packages (excludes newer libs)"

  build-libportal:
    description: "Build libportal from source on Linux"

outputs:
  vcpkg-cmake-config:
    description: "Windows vcpkg output for cmake"
    value: ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}

runs:
  using: "composite"

  steps:
    # TODO: This seems like it would be more useful as an standalone bash script.
    - name: Install dependencies
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            
            brew install cmake googletest ninja openssl --quiet

          elif [ "$RUNNER_OS" == "Linux" ]; then
            if [ ${{ inputs.os-like }} == "debian" ]; then

              apt update -qqq > /dev/null
              apt install -qqq cmake build-essential ninja-build \
                xorg-dev libx11-dev libxtst-dev libssl-dev \
                libglib2.0-dev libgdk-pixbuf-2.0-dev libnotify-dev \
                libxkbfile-dev qt6-base-dev qt6-tools-dev \
                libgtk-3-dev libgtest-dev libgmock-dev libpugixml-dev \
                libcli11-dev -y >/dev/null

              if [ "${{ inputs.legacy-debian }}" != "true" ]; then
                apt install -qqq libportal-dev libei-dev -y >/dev/null
              else
                echo "Skipping newer libs for legacy debian compatibility"
              fi

            elif [ ${{ inputs.os-like }} == "fedora" ]; then

              dnf install -y cmake make ninja-build gcc-c++ \
                rpm-build openssl-devel glib2-devel \
                gdk-pixbuf2-devel libXtst-devel libnotify-devel \
                libxkbfile-devel qt6-qtbase-devel qt6-qttools-devel \
                gtk3-devel gtest-devel gmock-devel pugixml-devel \
                libei-devel libportal-devel tomlplusplus-devel \
                cli11-devel

            elif [ ${{ inputs.os-like }} == "suse" ]; then

              zypper refresh
              zypper install -y --force-resolution \
                cmake make ninja gcc-c++ rpm-build libopenssl-devel \
                glib2-devel gdk-pixbuf-devel libXtst-devel libnotify-devel \
                libxkbfile-devel qt6-base-devel qt6-tools-devel gtk3-devel \
                googletest-devel googlemock-devel pugixml-devel libei-devel \
                libportal-devel tomlplusplus-devel cli11-devel

            elif [ ${{ inputs.like }} == "arch" ]; then

              pacman -Syu --noconfirm base-devel cmake ninja \
                gcc openssl glib2 gdk-pixbuf2 libxtst libnotify \
                libxkbfile gtest pugixml libei libportal \
                qt6-base qt6-tools gtk3 tomlplusplus cli11

            else
              echo "Unknown OS like: ${{ inputs.os-like }}"
            fi
          else
            echo "Unknown OS: $RUNNER_OS"
          fi
      shell: bash

    # HACK: This installs the system deps a 2nd time, but without that the Meson step fails.
    - name: Build libportal
      if: ${{ inputs.build-libportal }}
      run: |
        ./scripts/install_deps.py \
        --meson-no-system libportal --meson-static libportal --subprojects
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive

    # HACK: Needed for GTest on Windows (installed bia Meson).
    - name: Install Windows deps
      if: ${{ runner.os == 'Windows' }}
      shell: pwsh
      run: |
        echo "Installing Windows dependencies"
        python ./scripts/install_deps.py --skip-vcpkg

    - name: Install Qt (macOS)
      if: ${{ runner.os == 'macOS' }}
      uses: jurplel/install-qt-action@v4
      env:
        AQT_CONFIG: ${{ github.workspace }}/.github/workflows/aqt.ini
      with:
        dir: "/Users/runner"
        version: ${{ inputs.qt-version }}
        cache: true
        cache-key-prefix: macos-qt-${{ inputs.qt-version }}

    - name: Install Qt (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: jurplel/install-qt-action@v4
      env:
        AQT_CONFIG: ${{ github.workspace }}/.github/workflows/aqt.ini
      with:
        dir: "C:"
        version: ${{ inputs.qt-version }}
        cache: true
        cache-key-prefix: windows-qt-${{ inputs.qt-version }}

    # Install Ninja with an action instead of using Chocolatey, as it's more
    # reliable and faster. The Ninja install action is pretty good as it
    # downloads directly from the `ninja-build` GitHub project releases.
    - name: Install Ninja
      if: ${{ runner.os == 'Windows' }}
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build and cache vcpkg
      if: ${{ runner.os == 'Windows' }}
      id: vcpkg
      uses: sithlord48/vcpkg-action@v7
      with:
        manifest-dir: ${{ github.workspace }}
        triplet: x64-windows-release
        token: ${{ github.token }}

    # This effectively runs `vcvarsall.bat`, etc. It's not actually installing
    # VC++ as that's already pre-installed on the Windows runner.
    - name: Setup VC++ environment
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Wix
      if: ${{ runner.os == 'Windows' }}
      run: |
        dotnet tool install --global wix --version 5.0.2
        wix extension add --global WixToolset.UI.wixext/5.0.2
        wix extension add --global WixToolset.Util.wixext/5.0.2
        wix extension add --global WixToolset.Firewall.wixext/5.0.2
      shell: pwsh
