name: "Copy binaries for distribution"

runs:
  using: "composite"

  steps:
    - run: |
        cd build/bin
        mkdir -p ../../dist
        ls -al *

        if [ "${{ runner.os }}" == "Windows" ]; then

          if [ ! -f synergy-core.exe ]; then
            echo "Unified core not found, skipping copy."
            exit 0
          fi
          
          cp -v \
            synergy-core.exe \
            syntool.exe \
            libcrypto-3-x64.dll \
            libssl-3-x64.dll \
            ../../dist/
        else

          if [ ! -f synergy-core ]; then
            echo "Unified core not found, skipping copy."
            exit 0
          fi

          cp -v \
            synergy-core \
            syntool \
            ../../dist/
        fi
      shell: bash
