name: "Run tests"
description: "Runs both unit tests and legacy tests"

inputs:
  bin-dir:
    description: "The directory containing the test binaries"
    default: "build/bin"

runs:
  using: "composite"

  steps:
    - name: Unit Tests
      id: unit-tests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        ctest --test-dir "build/src/unittests" --output-on-failure || result=1
        ctest --test-dir "build/extra/src/unittests" --output-on-failure || result=1

        if [ "${result:-0}" -ne 0 ]; then
          echo "Unit tests failed" >> $GITHUB_STEP_SUMMARY
          exit 1
        fi
      shell: bash
      continue-on-error: true

    - name: Legacy Tests
      id: legacy-tests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        ./${{ inputs.bin-dir }}/legacytests
        result=$?

        if [ $result -ne 0 ]; then
          echo "Legacy tests failed with code: $result" >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
      continue-on-error: true

    - name: Check test outcome
      if: (steps.unit-tests.outcome != 'success' || steps.legacy-tests.outcome != 'success')
      run: |
        echo "Tests failed"
        exit 1
      shell: bash
