name: CI comment

on:
  workflow_dispatch:
    inputs:
      test-sha:
        description: "Test Git SHA for PR to comment on"
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  call-shared:
    uses: symless/actions/.github/workflows/ci-comment.yml@master
